version: '3.8'
services:
  server:
    build:
      context: ./server
      target: development
    ports:
      - "8000:8000" # デバッグ用
      - "8080:8080" # 実行用
    restart: always
    tty: true
    environment:
      - SERVER_PORT=8080
    volumes:
      - ./server:/app